# Boilerplate code generated by OVITO Pro 3.5.4
from ovito.io import *
from ovito.modifiers import *
from ovito.pipeline import *
from ovito.vis import *

# Data import:
pipeline = import_file('/home/andebraa/master/initial_system/erratic/system_or100_hi115_errgrid3_*.data', atom_style = 'atomic')
pipeline.add_to_scene()

# Slice:
pipeline.modifiers.append(SliceModifier(
    distance = 200.4062, 
    inverse = True))

# Slice:
pipeline.modifiers.append(SliceModifier(
    distance = 100.40620000000001, 
    normal = (0.0, 1.0, 0.0)))

# Viewport setup:
vp = Viewport(
    type = Viewport.Type.Ortho, 
    fov = 107.77779497713433, 
    camera_dir = (0.4940508840141648, 0.8471859907837395, -0.1954216493242139), 
    camera_pos = (215.5508800663772, 110.87863062339056, 56.959484272606296))

# Rendering:
vp.render_image(filename='image.png', size=(640, 480))
